---
datacenter:
  children:
    routers:
      hosts:
        172.16.60.25:
        172.16.20.24:
      vars:
        testVar: 999
  vars:
    ansible_connection: network_cli
    ansible_network_os: nxos
    ansible_user: admin
    ansible_ssh_pass: admin
    ntp_servers: 129.6.15.28
